# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-02 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lagnuage',
            new_name='language',
        ),
    ]
