# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-02 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190702_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expected_cmd',
            field=models.CharField(default='language', max_length=100),
        ),
    ]
