# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-02 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lagnuage', models.CharField(default='ru', max_length=3)),
                ('login', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
