# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_user_expected_cmd'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_act',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='second_act',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
